export const CartActionTypes = {
    ADD_CART_ITEM: "ADD_CART_ITEM",
    REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
    FETCH_CART_ITEMS: "FETCH_CART_ITEMS",
    CLEAR_CART_ITEM: "CLEAR_CART_ITEM",
    CALCULATE_CART_TOTAL: "CALCULATE_CART_TOTAL",
};
