export const ProductActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_COLLECTIONS: "FETCH_COLLECTIONS",
    ADD_CURRENT_PRODUCT: "ADD_CURRENT_PRODUCT",
};
