export const ProductActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_PRODUCTS_IDS: "FETCH_PRODUCTS_IDS",
    FETCH_CATEGORIES_IDS: "FETCH_CATEGORIES_IDS",
};
